[workspace]
resolver = "2"
members = [
    "spine",
    "polydigest",
    "cml",
    "eml",
    "cmt",
    "emt",
    "storage-fjall",
    "examples",
]

[workspace.package]
authors = ["Timothy DeHerrera <tim@nrdxp.dev>"]
keywords = ["merkle", "proof", "log", "tree", "cryptography"]
categories = ["algorithms", "cryptography", "data-structures"]
