//! RFC 9162 proof generation and verification for TSML.
//!
//! Implements the standard Merkle tree proof algorithms adapted for
//! `Vec<u8>` digests and `dyn Hasher`. These are free functions — they
//! operate on leaf hash sequences, not on `Log` state.

use crate::Hasher;

// ============================================================================
// Tree helpers
// ============================================================================

/// Largest power of 2 strictly less than `n`.
///
/// Defined for `n > 1`. Panics if `n <= 1`.
pub(crate) fn largest_pow2_lt(n: usize) -> usize {
    debug_assert!(n > 1, "largest_pow2_lt requires n > 1, got {n}");
    1 << (usize::BITS - 1 - (n - 1).leading_zeros())
}

/// Batch Merkle Tree Hash (RFC 9162 §2.1).
///
/// Computes the root hash of an ordered list of leaf hashes using the
/// recursive definition. Used internally for proof generation.
pub(crate) fn mth(hasher: &dyn Hasher, leaves: &[Vec<u8>]) -> Vec<u8> {
    match leaves.len() {
        0 => hasher.empty(),
        1 => leaves[0].clone(),
        n => {
            let k = largest_pow2_lt(n);
            let left = mth(hasher, &leaves[..k]);
            let right = mth(hasher, &leaves[k..]);
            hasher.node(&left, &right)
        },
    }
}

// ============================================================================
// Proof generation (free functions)
// ============================================================================

/// PATH algorithm for inclusion proofs (RFC 9162 §2.1.3).
///
/// Recursively computes the sibling hashes from leaf `m` to the root.
pub(crate) fn gen_path(hasher: &dyn Hasher, m: usize, leaves: &[Vec<u8>]) -> Vec<Vec<u8>> {
    let n = leaves.len();
    if n == 1 {
        return Vec::new();
    }
    let k = largest_pow2_lt(n);
    if m < k {
        let mut result = gen_path(hasher, m, &leaves[..k]);
        result.push(mth(hasher, &leaves[k..]));
        result
    } else {
        let mut result = gen_path(hasher, m - k, &leaves[k..]);
        result.push(mth(hasher, &leaves[..k]));
        result
    }
}

/// SUBPROOF algorithm for consistency proofs (RFC 9162 §2.1.4).
///
/// Recursively computes the intermediate hashes proving that the first
/// `m` leaves are a prefix of the `leaves` slice.
pub(crate) fn gen_subproof(
    hasher: &dyn Hasher,
    m: usize,
    leaves: &[Vec<u8>],
    b: bool,
) -> Vec<Vec<u8>> {
    let n = leaves.len();
    if m == n {
        if b {
            return Vec::new();
        } else {
            return vec![mth(hasher, leaves)];
        }
    }
    let k = largest_pow2_lt(n);
    if m <= k {
        let mut result = gen_subproof(hasher, m, &leaves[..k], b);
        result.push(mth(hasher, &leaves[k..]));
        result
    } else {
        let mut result = gen_subproof(hasher, m - k, &leaves[k..], false);
        result.push(mth(hasher, &leaves[..k]));
        result
    }
}

// ============================================================================
// Proof types
// ============================================================================

/// Inclusion proof — proves a leaf at `index` exists in a tree of `tree_size`.
///
/// Generated by [`Log::inclusion_proof`](crate::Log::inclusion_proof) and
/// verified by [`verify_inclusion`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InclusionProof {
    /// 0-based leaf index.
    pub index: u64,
    /// Size of the tree for which this proof is valid.
    pub tree_size: u64,
    /// Sibling hashes from leaf to root.
    pub path: Vec<Vec<u8>>,
}

/// Consistency proof — proves a tree of `old_size` is a prefix of `new_size`.
///
/// Generated by [`Log::consistency_proof`](crate::Log::consistency_proof) and
/// verified by [`verify_consistency`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConsistencyProof {
    /// Size of the older tree.
    pub old_size: u64,
    /// Size of the newer tree.
    pub new_size: u64,
    /// Intermediate hashes.
    pub path: Vec<Vec<u8>>,
}

// ============================================================================
// Proof verification (standalone — no Log needed)
// ============================================================================

/// Verify an inclusion proof (RFC 9162 §2.1.3.2).
///
/// Returns `true` if the proof demonstrates that `leaf_hash` is the leaf at
/// `proof.index` in a tree of `proof.tree_size` with the given `root`.
///
/// This is a standalone verifier — no [`Log`](crate::Log) is needed.
pub fn verify_inclusion(
    hasher: &dyn Hasher,
    leaf_hash: &[u8],
    proof: &InclusionProof,
    root: &[u8],
) -> bool {
    if proof.index >= proof.tree_size {
        return false;
    }

    let mut fn_ = proof.index;
    let mut sn = proof.tree_size - 1;
    let mut r = leaf_hash.to_vec();

    for p in &proof.path {
        if sn == 0 {
            return false;
        }
        if (fn_ & 1 == 1) || fn_ == sn {
            r = hasher.node(p, &r);
            while fn_ & 1 == 0 && fn_ != 0 {
                fn_ >>= 1;
                sn >>= 1;
            }
        } else {
            r = hasher.node(&r, p);
        }
        fn_ >>= 1;
        sn >>= 1;
    }

    sn == 0 && r == root
}

/// Verify a consistency proof (RFC 9162 §2.1.4.2).
///
/// Returns `true` if the proof demonstrates that the tree of `proof.old_size`
/// with `old_root` is a prefix of the tree of `proof.new_size` with `new_root`.
///
/// This is a standalone verifier — no [`Log`](crate::Log) is needed.
pub fn verify_consistency(
    hasher: &dyn Hasher,
    proof: &ConsistencyProof,
    old_root: &[u8],
    new_root: &[u8],
) -> bool {
    if proof.old_size == 0 || proof.old_size >= proof.new_size {
        return false;
    }

    // Build the effective path: if old_size is a power of 2, prepend old_root.
    let path: Vec<&[u8]> = if proof.old_size.is_power_of_two() {
        std::iter::once(old_root)
            .chain(proof.path.iter().map(|v| v.as_slice()))
            .collect()
    } else {
        proof.path.iter().map(|v| v.as_slice()).collect()
    };

    if path.is_empty() {
        return false;
    }

    let mut fn_ = proof.old_size - 1;
    let mut sn = proof.new_size - 1;

    // Strip common prefix of trailing ones.
    while fn_ & 1 == 1 {
        fn_ >>= 1;
        sn >>= 1;
    }

    let mut fr = path[0].to_vec();
    let mut sr = path[0].to_vec();

    for c in &path[1..] {
        if sn == 0 {
            return false;
        }
        if (fn_ & 1 == 1) || fn_ == sn {
            fr = hasher.node(c, &fr);
            sr = hasher.node(c, &sr);
            while fn_ & 1 == 0 && fn_ != 0 {
                fn_ >>= 1;
                sn >>= 1;
            }
        } else {
            sr = hasher.node(&sr, c);
        }
        fn_ >>= 1;
        sn >>= 1;
    }

    sn == 0 && fr == old_root && sr == new_root
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use sha2::{Digest, Sha256};

    #[derive(Debug)]
    struct Sha256Hasher;

    impl Hasher for Sha256Hasher {
        fn leaf(&self, data: &[u8]) -> Vec<u8> {
            let mut h = Sha256::new();
            h.update([0x00]);
            h.update(data);
            h.finalize().to_vec()
        }
        fn node(&self, left: &[u8], right: &[u8]) -> Vec<u8> {
            let mut h = Sha256::new();
            h.update([0x01]);
            h.update(left);
            h.update(right);
            h.finalize().to_vec()
        }
        fn empty(&self) -> Vec<u8> {
            Sha256::digest(b"").to_vec()
        }
        fn null(&self) -> Vec<u8> {
            Sha256::digest([0x02]).to_vec()
        }
        fn digest_len(&self) -> usize {
            32
        }
    }

    #[test]
    fn largest_pow2_lt_cases() {
        assert_eq!(largest_pow2_lt(2), 1);
        assert_eq!(largest_pow2_lt(3), 2);
        assert_eq!(largest_pow2_lt(4), 2);
        assert_eq!(largest_pow2_lt(5), 4);
        assert_eq!(largest_pow2_lt(8), 4);
        assert_eq!(largest_pow2_lt(9), 8);
        assert_eq!(largest_pow2_lt(16), 8);
        assert_eq!(largest_pow2_lt(17), 16);
    }

    #[test]
    fn mth_matches_incremental() {
        let h = Sha256Hasher;
        let leaves: Vec<Vec<u8>> = (0..7u8).map(|i| h.leaf(&[i])).collect();
        let batch = mth(&h, &leaves);

        // Cross-check: build incrementally via manual tree construction.
        // For 7 leaves, the tree structure is:
        //         root
        //        /    \
        //      n4      n3 (odd, promoted from right)
        //     / \     / \
        //   n2   n2  n1  leaf[6]
        //  / \ / \  / \
        // 0 1 2 3 4 5
        let n01 = h.node(&leaves[0], &leaves[1]);
        let n23 = h.node(&leaves[2], &leaves[3]);
        let n45 = h.node(&leaves[4], &leaves[5]);
        let n0123 = h.node(&n01, &n23);
        let n456 = h.node(&n45, &leaves[6]);
        let expected = h.node(&n0123, &n456);
        assert_eq!(batch, expected);
    }

    #[test]
    fn inclusion_proof_single_leaf() {
        let h = Sha256Hasher;
        let leaves = vec![h.leaf(b"only")];
        let root = mth(&h, &leaves);
        let path = gen_path(&h, 0, &leaves);
        assert!(path.is_empty());

        let proof = InclusionProof {
            index: 0,
            tree_size: 1,
            path,
        };
        assert!(verify_inclusion(&h, &leaves[0], &proof, &root));
    }

    #[test]
    fn inclusion_proof_roundtrip() {
        let h = Sha256Hasher;
        for size in [2, 3, 4, 5, 7, 8, 9, 15, 16, 17] {
            let leaves: Vec<Vec<u8>> = (0..size as u8).map(|i| h.leaf(&[i])).collect();
            let root = mth(&h, &leaves);

            for idx in 0..size {
                let path = gen_path(&h, idx, &leaves);
                let proof = InclusionProof {
                    index: idx as u64,
                    tree_size: size as u64,
                    path,
                };
                assert!(
                    verify_inclusion(&h, &leaves[idx], &proof, &root),
                    "inclusion proof failed: size={size}, idx={idx}"
                );

                // Wrong leaf should fail.
                let wrong_leaf = h.leaf(b"wrong");
                assert!(
                    !verify_inclusion(&h, &wrong_leaf, &proof, &root),
                    "wrong leaf should not verify: size={size}, idx={idx}"
                );
            }
        }
    }

    #[test]
    fn consistency_proof_roundtrip() {
        let h = Sha256Hasher;
        let max_size = 16;
        let all_leaves: Vec<Vec<u8>> = (0..max_size as u8).map(|i| h.leaf(&[i])).collect();

        for old_size in 1..max_size {
            for new_size in (old_size + 1)..=max_size {
                let old_root = mth(&h, &all_leaves[..old_size]);
                let new_root = mth(&h, &all_leaves[..new_size]);

                let path = gen_subproof(&h, old_size, &all_leaves[..new_size], true);
                let proof = ConsistencyProof {
                    old_size: old_size as u64,
                    new_size: new_size as u64,
                    path,
                };
                assert!(
                    verify_consistency(&h, &proof, &old_root, &new_root),
                    "consistency proof failed: old={old_size}, new={new_size}"
                );
            }
        }
    }
}
